### ISSUE TITLE
Change office hours requirement

### ISSUE THREAD

**Issue by newsch** [olin/studentgovernment#46]
Lack of attendance at office hours has been a discussion for as long as I've been on CORe.
This year we did a month-long trial with mixed results. At the [2018-10-09 meeting](https://docs.google.com/document/d/1D5FEFE9Srvu7g0vYHPTDJV3keZvoTFGPz1zlMcYBTGw/edit#heading=h.u5j8d0nym5ln) we discussed some possible alternatives, mainly having individuals present some form of engagement with the student body on a monthly basis.

**Comment by anushadatar** [comment]
Doesn't look like there's a codified place for this where it is required in the by-laws. I'd like to think that we can handle community engagement in a flexible way; when it makes sense to host a chill event, we can do that, and when it makes sense to do serious office hours, we can do that. I'd propose closing this issue because the by-laws already emphasize the expectation of community engagement anyways, so I am not sure that needs to happen more explicitly.

Regardless, this will be discussed at the 12/4/2019 meeting.

**Comment by anushadatar** [comment]
We discussed this at the [12/5](https://docs.google.com/document/d/1uFAjqx9bZrjbd-uN2i57kGZg_zhPvtcGLRUWuzWtOYM/edit?usp=sharing) and then decided that office hours is likely not the way to address codifying community engagement for members of CORe. Closing this issue.
